version: '3.8'

services:
  jenkins_instance:
    container_name: jenkins_con
    # image: jenkins/jenkins
    image: jenkins-ansible:v2.0.0
    build: 
      context: .
      dockerfile: docker/jenkins-ansible/Dockerfile.jenkinsansible
    # user: root 
    # previleged: true
    ports:
      - "8082:8080"  # Jenkins web UI
      # - "50000:50000"  # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net
    # environment:
    #   JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"  # Disable initial setup wizard
  
  remote_host:
    container_name: remote-host-ssh
    image: remote-host-ssh:v2.0.0
    build:
      context: .
      dockerfile: docker/ssh/Dockerfile.centos
      # dockerfile: docker/ssh/Dockerfile.debian12
      # dockerfile: docker/ssh/Dockerfile.rockey9 
      # dockerfile: docker/ssh/Dockerfile.alpinlinux
      # dockerfile: docker/ssh/Dockerfile.fedora38
      # dockerfile: docker/ssh/Dockerfile.archlinux
      # dockerfile: docker/ssh/Dockerfile.ubuntojammyjellyfish 
    networks:
      - jenkins_net
    ports:
      - "2222:22"
    
  mariadb_db_instance:
    container_name: test-db
    image: test-db-image:v2.0.0
    build: 
      context: .
      dockerfile: docker/db/Dockerfile.mariadb
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: brotecs1230
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: brotecs1230
    volumes:
      - db-data-vol:/var/lib/mysql
    networks:
      - jenkins_net
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  
  phpmyadmin_instance:
    container_name: test-dbmanager
    image: phpmyadmin:latest
    links:
      - mariadb_db_instance
    networks:
      - jenkins_net
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8081:80
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M


networks:
  jenkins_net:
    driver: bridge


volumes:
  jenkins_home:
  db-data-vol:
  jenkins-docker-certs:








