---
services:
  jenkins_instance:
    container_name: jenkins_con
    image: jenkins-test-image:v2.0.0
    build: 
      context: .
      dockerfile: docker/jenkins-ansible/Dockerfile.jenkinsansible
    ports:
      - "8082:8080"  # Jenkins web UI  mosharaf/brotecs
      # - "50000:50000" # Agent communication.
    volumes:
      - var-jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # - jenkins-temp-vol:/tmp
      - ./dist/extrascript/script.sh:/tmp/script.sh 
      - ./dist/ssh-key/remote-key:/tmp/ansible/remote-key
      - ./dist/ansible/inventory/hosts:/tmp/ansible/hosts
      - ./dist/ansible/pbook/inven.ini:/tmp/ansible/inven.ini
      - ./dist/ansible/pbook/:/tmp/ansible/pbook
      - ./dist/db/jenkins-ansible_db.sh:/tmp/jenkins-ansible_db.sh
      - ./dist/db/jenkins_people_db.txt:/tmp/jenkins_people_db.txt
    networks:
      jenkins_net:
        ipv4_address: 192.168.1.100

    # environment:
    #   JENKINS_OPTS="--prefix=/jenkins" # Sets the Jenkins web context path.
    #   JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"  # Disable initial setup wizard
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 512M
    # depends_on:
    #   - client1_remote
    #   - client2_remote
    #   - test-db

# wait it,s takes time to start the container of gitlab
# if register and login user issue on gitlab the attach the container and run the command 
#  docker exec -it gitlab bash
#  gitlab-ctl restart
# git clone http://gitlab.example.com:8929/jenkins/jenkins_test_project1.git
  gitlab:
    image: gitlab/gitlab-ee:latest  #Current version: gitlab-ee=17.9.1-ee.0 
    container_name: gitlab   #username/password:  mosharaf / 9/fbH=/M4jugXyB
    restart: on-failure
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      # - '8099:80'
      - '8929:8929'
      # - '443:443'
      # - '2424:22'
    volumes:
      - data_opt_gitlab:/var/opt/gitlab'
      - logs_gitlab:/var/log/gitlab
      - config_etc_gitlab:/etc/gitlab
    shm_size: '256m'
    networks:
      jenkins_net:
        ipv4_address: 192.168.1.106
    
  client1_remote:
    container_name: client1_remote
    image: client1_remote-image:v2.0.0
    volumes:
      - backup-temp-c1:/tmp
    build:
      context: .
      dockerfile: docker/ssh-os/Dockerfile.debian12  # mh pass: 1234, user2 pass, root pass
      # docker/ssh-os/Dockerfile.debian_only_root
      # docker/ssh-os/Dockerfile.debian12  # mh pass: 1234, user2 pass, root pass
      # docker/ssh-os/Dockerfile.debian12.passless
      # docker/ssh-os/Dockerfile.debian12.passwithkey
      # dockerfile: docker/ssh-os/Dockerfile.centos
      # dockerfile: docker/ssh-os/Dockerfile.rockey9 
      # dockerfile: docker/ssh-os/Dockerfile.alpinlinux
      # dockerfile: docker/ssh-os/Dockerfile.fedora38
      # dockerfile: docker/ssh-os/Dockerfile.archlinux
      # dockerfile: docker/ssh-os/Dockerfile.ubuntojammyjellyfish 
    networks:
      jenkins_net:
        ipv4_address: 192.168.1.101
    ports:
      - "2222:22"
      - "8090:80"

  client2_remote:
    container_name: client2_remote
    image: client2_remote-image:v2.0.0
    volumes:
      - backup-temp-c2:/tmp
    build:
      context: .
      dockerfile: docker/ssh-os/Dockerfile.debian12.root # user1 pass:1234 + root pass  +  passless no pass based user 
      # docker/ssh-os/Dockerfile.debian12.passless
      # docker/ssh-os/Dockerfile.debian12
      # docker/ssh-os/Dockerfile.debian12.org
      # dockerfile: docker/ssh-os/Dockerfile.centos
      # dockerfile: docker/ssh-os/Dockerfile.rockey9 
      # dockerfile: docker/ssh-os/Dockerfile.alpinlinux
      # dockerfile: docker/ssh-os/Dockerfile.fedora38
      # dockerfile: docker/ssh-os/Dockerfile.archlinux
      # dockerfile: docker/ssh-os/Dockerfile.ubuntojammyjellyfish 
    networks:
      jenkins_net:
        ipv4_address: 192.168.1.102
    ports:
      - "2223:22"
      - "8091:80"
      
    
  # it is working but skip for now down below 
  web:
    container_name: web-ansible
    image: web-ansible-image:v1.0.0
    build: 
      context: .
      dockerfile: docker/web/Dockerfile.webdebian
      # dockerfile: docker/web/Dockerfile.webcentos
    ports:
      - "8088:80"
    networks:
      jenkins_net:
        ipv4_address: 192.168.1.103
    depends_on:
      - client1_remote
      - mariadb_db_instance
    # volumes:
      # - "./www/source:/var/www/html"  # permission related issue fixed by dockerfile

  mariadb_db_instance:
    container_name: test-db
    image: db-test-image:v2.0.0
    build: 
      context: .
      dockerfile: docker/db/Dockerfile.mariadb

    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: brotecs1230
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: brotecs1230
    volumes:
      - db-data-vol:/var/lib/mysql
      - ./dist/db/jenkins-ansible_db.sh:/tmp/jenkins-ansible_db.sh
      - ./dist/db/jenkins_people_db.txt:/tmp/jenkins_people_db.txt
    networks:
      jenkins_net:
        ipv4_address: 192.168.1.104
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  
  phpmyadmin_instance:
    container_name: test-dbmanager
    image: phpmyadmin:latest
    links:
      - mariadb_db_instance
    networks:
      jenkins_net:
        ipv4_address: 192.168.1.105
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8081:80
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M


networks:
  jenkins_net:
    driver: bridge
    name: jenkins_net
    ipam:
      # driver: default
      config:
        - subnet: 192.168.1.0/24



volumes:
  var-jenkins_home:
    name: var-jenkins_home
  db-data-vol:
    name: db-data-vol
  backup-temp-c1:
    name: backup-temp-c1
  backup-temp-c2:
    name: backup-temp-c2
  data_opt_gitlab: 
    name: opt_gitlab
  logs_gitlab:
    name: logs_gitlab
  config_etc_gitlab:
    name: config_etc_gitlab
    
  # jenkins-temp-vol:
  #   name: jenkins-temp-vol


# one named volume to another named volume copy
# docker run --rm -it  -v  devops-jenkins-docker_var-jenkins_home:/from -v var-jenkins_home:/to  nginx bash -c "cd /from ; cp -av . /to"
# docker run --rm -it  -v  devops-jenkins-docker_db-data-vol:/from -v db-data-vol:/to  nginx bash -c "cd /from ; cp -av . /to"
