version: '3.8'

services:
  jenkins_instance:
    container_name: jenkins_con
    image: jenkins-test-image:v2.0.0
    build: 
      context: .
      dockerfile: docker/jenkins-ansible/Dockerfile.jenkinsansible
    ports:
      - "8082:8080"  # Jenkins web UI
    volumes:
      - var-jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dist/script.sh:/tmp/script.sh 
      - ./dist/play.yml:/var/jenkins_home/ansible/play.yml
    networks:
      - jenkins_net
    # environment:
    #   JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"  # Disable initial setup wizard
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    depends_on:
      - remote_host
      - mariadb_db_instance
  
  remote_host:
    container_name: remote-host-ssh
    image: remote-host-ssh-test-image:v2.0.0
    build:
      context: .
      # dockerfile: docker/ssh/Dockerfile.debian12
      dockerfile: docker/ssh/Dockerfile.centos
      # dockerfile: docker/ssh/Dockerfile.rockey9 
      # dockerfile: docker/ssh/Dockerfile.alpinlinux
      # dockerfile: docker/ssh/Dockerfile.fedora38
      # dockerfile: docker/ssh/Dockerfile.archlinux
      # dockerfile: docker/ssh/Dockerfile.ubuntojammyjellyfish 
    networks:
      - jenkins_net
    ports:
      - "2222:22"
    
  web:
    container_name: web-ansible
    image: web-ansible-image:v1.0.0
    build: 
      context: .
      dockerfile: docker/web/Dockerfile.web
    ports:
      - "8080:80"
    networks:
      - jenkins_net
    depends_on:
      - remote_host
      - mariadb_db_instance

  mariadb_db_instance:
    container_name: test-db
    image: db-test-image:v2.0.0
    build: 
      context: .
      dockerfile: docker/db/Dockerfile.mariadb
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: brotecs1230
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: brotecs1230
    volumes:
      - db-data-vol:/var/lib/mysql
    networks:
      - jenkins_net
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  
  phpmyadmin_instance:
    container_name: test-dbmanager
    image: phpmyadmin:latest
    links:
      - mariadb_db_instance
    networks:
      - jenkins_net
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8081:80
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M


networks:
  jenkins_net:
    driver: bridge


volumes:
  var-jenkins_home:
  db-data-vol:








