FROM --platform=linux/amd64 debian:12-slim

RUN apt-get update && \
    apt-get install -y openssh-server && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /run/sshd

# Create user1 with password-based SSH
RUN useradd -m mh1 && \
    echo "mh1:brotecs1230" | chpasswd && \
    mkdir /home/mh1/.ssh && \
    chmod 700 /home/mh1/.ssh

# Create mh2 with SSH key-based authentication
RUN useradd -m mh2 && \
    mkdir /home/mh2/.ssh && \
    chmod 700 /home/mh2/.ssh

COPY ./dist/ssh-key/remote-key.pub /home/mh2/.ssh/authorized_keys
RUN chown mh2:mh2 -R /home/mh2/.ssh/ && \
    chmod 600 /home/mh2/.ssh/authorized_keys

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config && \
    echo "AllowUsers mh1 mh2" >> /etc/ssh/sshd_config

RUN apt-get update && apt-get install -y  \
    net-tools \
    telnet \
    procps \
    iputils-ping \
    python3 \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 22

# Start the SSH service
ENTRYPOINT ["/usr/sbin/sshd", "-D"]
