FROM --platform=linux/amd64 debian:12-slim

RUN apt-get update && \
    apt-get install -y openssh-server && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /run/sshd

RUN useradd -m mh && \
    passwd -d mh

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config && \
    echo "AllowUsers mh" >> /etc/ssh/sshd_config && \
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "PermitEmptyPasswords yes" >> /etc/ssh/sshd_config && \
    echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config

RUN apt-get update && apt-get install -y \
    net-tools \
    telnet \
    procps \
    iputils-ping \
    python3 \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 22

# Start the SSH service
ENTRYPOINT ["/usr/sbin/sshd", "-D"]
