FROM remote-host-ssh-test-image:v2.0.0
# FROM centos:8

RUN dnf install -y epel-release && \
    dnf install -y \
    nginx \
    php \
    php-fpm \
    php-mysqli \
    php-pdo \
    php-pdo_mysql \
    php-soap \
    php-xml \
    php-zip \
    php-json \
    php-mbstring \
    php-gd \
    openssl && \
    dnf clean all

RUN sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' /etc/php.ini && \
    sed -i 's/user = apache/user = nginx/' /etc/php-fpm.d/www.conf && \
    sed -i 's/group = apache/group = nginx/' /etc/php-fpm.d/www.conf

WORKDIR /var/www/html

# RUN echo "<?php phpinfo(); ?>" > /var/www/html/index.php

RUN echo "<?php echo 'Hello World'; ?>" > /var/www/html/index.php

RUN chown -R nginx:nginx /var/www/html

VOLUME /var/www/html /var/log/nginx /var/log/php-fpm /var/lib/php-fpm


COPY ./dist/web/conf/nginx_cus.conf /etc/nginx/conf.d/default.conf
COPY ./dist/web/conf/nginx.conf /etc/nginx/nginx.conf

COPY ./dist/web/conf/start.sh /start.sh



RUN chmod +x /start.sh

EXPOSE 80 443 9000

ENTRYPOINT ["/start.sh"]
