FROM remote-host-ssh

COPY ./dist/web/conf/nginx.repo /etc/yum.repos.d/nginx.repo

RUN \
    yum install -y nginx-1.12.2 openssl --enablerepo=nginx && \
    yum install -y https://centos7.iuscommunity.org/ius-release.rpm && \
    yum install -y  \
    php71u-fpm \
    php71u-cli \
    php71u-mysqlnd \
    php71u-soap \
    php71u-xml \
    php71u-zip \ 
    php71u-json \
    php71u-mcrypt \
    php71u-mbstring \
    php71u-gd \
    enablerepo=ius &&  yum clean all

COPY ./dist/web/conf/nginx.conf /etc/nginx/nginx.conf


EXPOSE 80 443 

ENTRYPOINT ["nginx", "-g", "daemon off;"]

