FROM client1_remote-image:v2.0.0
# FROM debian:12

RUN apt-get update && \
    apt-get install -y \
    nginx \
    php \
    php-fpm \
    php-mysql \
    php-pdo \
    php-soap \
    php-xml \
    php-zip \
    php-json \
    php-mbstring \
    php-gd \
    openssl && \
    rm -rf /var/lib/apt/lists/*

RUN php -v

RUN PHP_VERSION=$(php -r "echo PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION;") && \
    sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' /etc/php/$PHP_VERSION/fpm/php.ini && \
    sed -i 's/user = www-data/user = nginx/' /etc/php/$PHP_VERSION/fpm/pool.d/www.conf && \
    sed -i 's/group = www-data/group = nginx/' /etc/php/$PHP_VERSION/fpm/pool.d/www.conf

RUN ls /etc/php/

USER root

WORKDIR /var/www/html

# RUN echo "<?php phpinfo(); ?>" > /var/www/html/index.php

# RUN echo "<?php echo 'Hello World'; ?>" > /var/www/html/index.php

COPY www/source/* /var/www/html/

RUN useradd -r -s /bin/false nginx && \
    chown -R nginx:nginx /var/www/html
# RUN chown -R www-data:www-data /var/www/html

VOLUME /var/www/html /var/log/nginx /var/log/php7.4-fpm /var/lib/php/fpm

COPY ./dist/web/conf/nginx_cus.conf /etc/nginx/conf.d/default.conf
COPY ./dist/web/conf/nginx.conf /etc/nginx/nginx.conf

COPY ./dist/web/conf/start_debian.sh /start.sh

RUN chmod +x /start.sh

EXPOSE 80 443 9000

ENTRYPOINT ["/start.sh"]
