#!/usr/bin/env groovy

def printSuccessMessage(message) {
    echo "\u001B[32m[SUCCESS]\u001B[0m ${message}"
}

def printFailMessage(message) {
    echo "\u001B[31m[FAIL]\u001B[0m ${message}"
}

def printWarningMessage(message) {
    echo "\u001B[33m[WARNING]\u001B[0m ${message}"
}

def printInfoMessage(message) {
    echo "\u001B[34m[INFO]\u001B[0m ${message}"
}

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {   // **Steps block is required**
                script {
                    sh 'echo "Build process done..."'
                    printSuccessMessage('Build DONE')
                }
            }
        }
    }

    post {
        success {
            script {
                printSuccessMessage('Automation Test Successful...')
            }
        }
        failure {
            script {
                printFailMessage('Automation Test Failed, issues need to be fixed...')
            }
        }
        always {
            echo 'Pipeline execution finished'
        }
    }
}
