# NOTE: in this setting http://192.168.10.59:8082/manage/configure 
# Jenkins Location
# Jenkins URL(http://192.168.10.59:8082/) need to properly set as your host IP , portkept same
# Otherwise UI will slow down the whole project

# FROM jenkins/jenkins:lts
FROM jenkins/jenkins:latest

LABEL maintainer="Mosharaf Hossain, Software Engineer, mosharaf111hossain@gmail.com" 

ARG DEBIAN_FRONTEND=noninteractive

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip pipx curl vim sshpass ansible \
    && rm -rf /var/lib/apt/lists/*


# Install AWS CLI using pipx
RUN pipx install awscli

# Optional packges: Uncomment these lines if you need net-tools, telnet, procps
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     net-tools \
#     telnet \
#     procps \
#     && rm -rf /var/lib/apt/lists/*   #Ensures future builds don’t re-download everything.

# Optional packges
# RUN apt-get update \ 
#     && apt-get install -y iputils-ping \
#     && rm -rf /var/lib/apt/lists/*


# docker engine installation
RUN apt-get update && \
    apt-get install ca-certificates && \
    install -m 0755 -d /etc/apt/keyrings 
COPY ./dist/web/dockerengine/gpg /etc/apt/keyrings/docker.asc 
RUN chmod a+r /etc/apt/keyrings/docker.asc  && \
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Add jenkins user to the docker group
RUN usermod -aG docker jenkins


USER jenkins
# id 
# uid=1000(jenkins) gid=1000(jenkins) groups=1000(jenkins),999(docker)
# DinD docker.sock permission issue on host pc apply this command
# sudo chown 1000:1000 /var/run/docker.sock 

RUN mkdir -p /tmp/ansible/ && chmod -R 755 /tmp/ansible
COPY ./dist/ssh-key/remote-key /tmp/ansible/remote-key

COPY ./dist/ansible/inventory/hosts /tmp/ansible/hosts  
COPY ./dist/ansible/pbook/ /tmp/ansible/pbook

COPY ./dist/db/jenkins-ansible_db.sh /tmp/jenkins-ansible_db.sh
COPY ./dist/db/jenkins_people_db.txt /tmp/jenkins_people_db.txt

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/usr/share/jenkins/jenkins.war"]

