FROM --platform=linux/amd64 debian:12-slim

RUN apt-get update && \
    apt-get install -y openssh-server && \
    apt-get clean

RUN mkdir -p /run/sshd

RUN echo "root:1234" | chpasswd

RUN useradd -m user1 && \
    echo "user1:1234" | chpasswd


RUN useradd -m passless && \
    passwd -d passless


# Setup SSH keys for user1 and root
RUN mkdir -p /home/user1/.ssh && \
    mkdir -p /root/.ssh 
COPY ./dist/ssh-key/remote-key.pub /home/user1/.ssh/authorized_keys 
COPY ./dist/ssh-key/remote-key.pub /root/.ssh/authorized_keys

RUN chmod 700 /home/user1/.ssh /root/.ssh && \
    chmod 600 /home/user1/.ssh/authorized_keys /root/.ssh/authorized_keys && \
    chown -R user1:user1 /home/user1/.ssh && \
    chown -R root:root /root/.ssh

# Modify sshd_config to allow SSH access
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    echo "AllowUsers user1 root passless" >> /etc/ssh/sshd_config && \
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "PermitEmptyPasswords yes" >> /etc/ssh/sshd_config && \
    echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config

RUN apt-get update && apt-get install -y \
    vim \
    net-tools \
    telnet \
    procps \
    iputils-ping \
    python3 \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# RUN apt update && apt install -y sudo
# RUN usermod -aG sudo user1
# RUN echo "user1 ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers


# Add a new user with a password
RUN useradd -m unixadm && echo "unixadm:1234" | chpasswd

# Optional: Add the user to specific groups (e.g., sudo)
RUN usermod -aG sudo unixadm

EXPOSE 22

ENTRYPOINT ["/usr/sbin/sshd", "-D"]
