FROM --platform=linux/amd64 debian:12-slim

RUN apt-get update && \
    apt-get install -y openssh-server && \
    apt-get clean

RUN mkdir -p /run/sshd

# Create user1 with password-based SSH
RUN useradd -m user1 && \
    echo "user1:user1password" | chpasswd

# Create user2 with SSH key-based authentication
RUN useradd -m user2 && \
    mkdir /home/user2/.ssh && \
    chmod 700 /home/user2/.ssh

COPY ./dist/ssh-key/user2-key.pub /home/user2/.ssh/authorized_keys
RUN chown user2:user2 -R /home/user2/.ssh/ && \
    chmod 600 /home/user2/.ssh/authorized_keys

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config && \
    echo "AllowUsers user1 user2" >> /etc/ssh/sshd_config

RUN apt-get update && apt-get install -y  \
    net-tools \
    telnet \
    procps \
    iputils-ping \
    python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 22

# Start the SSH service
ENTRYPOINT ["/usr/sbin/sshd", "-D"]
