FROM --platform=linux/amd64 debian:12-slim

## Install OpenSSH server 
RUN apt-get update && \
    apt-get install -y openssh-server && \
    apt-get clean

RUN mkdir -p /run/sshd
RUN useradd -m mh && \
    echo "mh:1234" | chpasswd && \
    mkdir /home/mh/.ssh && \
    chmod 700 /home/mh/.ssh

COPY ./dist/ssh-key/remote-key.pub /home/mh/.ssh/authorized_keys
RUN chown mh:mh -R /home/mh/.ssh/ && \
    chmod 600 /home/mh/.ssh/authorized_keys


RUN useradd -m user2 && \
    echo "user2:1234" | chpasswd

RUN echo "root:1234" | chpasswd

# Setup SSH keys for user2 and root
RUN mkdir -p /home/user2/.ssh && \
    mkdir -p /root/.ssh 
COPY ./dist/ssh-key/remote-key.pub /home/user2/.ssh/authorized_keys 
COPY ./dist/ssh-key/remote-key.pub /root/.ssh/authorized_keys

RUN chmod 700 /home/user2/.ssh /root/.ssh && \
    chmod 600 /home/user2/.ssh/authorized_keys /root/.ssh/authorized_keys && \
    chown -R user2:user2 /home/user2/.ssh && \
    chown -R root:root /root/.ssh

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    echo "AllowUsers mh user2 root" >> /etc/ssh/sshd_config
## end OpenSSH server

RUN apt-get update && apt-get install -y  \
    net-tools \
    telnet \
    procps \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y iputils-ping && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update \ 
    && apt-get install -y python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


RUN apt update && apt install -y sudo   

RUN usermod -aG sudo mh 
RUN echo "mh ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers


# Add a new user with a password
RUN useradd -m unixadm && echo "unixadm:1234" | chpasswd

# Optional: Add the user to specific groups (e.g., sudo)
RUN usermod -aG sudo unixadm

# Expose SSH port
EXPOSE 22

# Start the SSH service
ENTRYPOINT ["/usr/sbin/sshd", "-D"]

