FROM debian:12-slim

## Install OpenSSH server 
RUN apt-get update && \
    apt-get install -y openssh-server python3 vim && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /run/sshd

# Create users and set up their passwords
RUN useradd -m mh && \
    echo "mh:1234" | chpasswd && \
    mkdir /home/mh/.ssh && \
    chmod 700 /home/mh/.ssh
COPY ./dist/ssh-key/remote-key.pub /home/mh/.ssh/authorized_keys
RUN chmod 600 /home/mh/.ssh/authorized_keys && \
    chown -R mh:mh /home/mh/.ssh

RUN useradd -m user2 && \
    echo "user2:1234" | chpasswd && \
    mkdir -p /home/user2/.ssh && \
    chmod 700 /home/user2/.ssh 
COPY ./dist/ssh-key/remote-key.pub /home/user2/.ssh/authorized_keys
RUN chmod 600 /home/user2/.ssh/authorized_keys && \
    chown -R user2:user2 /home/user2/.ssh

RUN echo "root:1234" | chpasswd && \
    mkdir -p /root/.ssh && \
    chmod 700 /root/.ssh
COPY ./dist/ssh-key/remote-key.pub /root/.ssh/authorized_keys 
RUN chmod 600 /root/.ssh/authorized_keys && \
    chown -R root:root /root/.ssh

# Modify sshd_config to allow SSH access
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    echo "AllowUsers mh user2 root" >> /etc/ssh/sshd_config && \
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config


RUN useradd -m unixadm && echo "unixadm:1234" | chpasswd


EXPOSE 80 22

ENTRYPOINT ["/usr/sbin/sshd", "-D"]
